name: QuantumSell
version: 1.1
main: me.quantum.QuantumSell.QuantumSell
api-version: 1.13
depend: [Vault]
commands:
  sell:
    description: Eladási menü megnyitása.
  selladmin:
    description: Adminisztrátori parancsok (add, list, reload, wipe).
    permission: sellgui.admin
