name: QuantumSell
version: 1.0
main: me.quantum.sellgui.QuantumSell
api-version: 1.13
depend: [Vault]
commands:
	sell:
		description: Eladas GUI megnyitasa
	selladmin:
		description: Admin parancsok (add, wipe)
